### ISSUE TITLE
Service can't be accessed from outside the ogn-receiver

### ISSUE THREAD

**Issue by Ventusfahrer** [Meisterschueler/ogn-control#18]
This is because the flask server is starting using the localhost ip-address only (127.0.0.1)
To access the flask server from net network you should start the flask app as:

flask run --host='0.0.0.0'

**Comment by Meisterschueler** [comment]
Thank you for the hint.
Fixed with 2460111b59727bc39c37e2b68b7ef0dcb69e090e
